DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(),name='index'),
    #/food/1
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('item/', views.item,name='item'),
    # add items
    path('add',views.CreateItem.as_view(), name='create_item'),
    # edit
    path('update/<int:id>/',views.update_item, name='update_item'),
    # delete
    path('delete/<int:id>/',views.delete_item, name='delete_item'),


]

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import  reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
            return reverse("food:detail", kwargs={"pk": self.pk})

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']


DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

def index(request):
    item_list = Item.objects.all()

    context = {
        'item_list':item_list,
    }
    return render(request,'food/index.html', context)

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html', {'form':form})

# this is a clase based view for create item

class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html',{'form': form, 'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html',{'item':item})





DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/views.py
from django.shortcuts import redirect,render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
       form = RegisterForm(request.POST)
       if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created ')
            return redirect('login')
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Food App</title>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
	  <div class="container-fluid ">
		<a class="navbar-brand " href="#">JMRFood App</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse " id="navbarSupportedContent">
		  <ul class="navbar-nav ms-auto">

			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url 'food:create_item' %}">Add Item</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="#">Delete Item</a>
			</li>
			  <li class="nav-item">
			  <a class="nav-link" href="#">View Item</a>
			 </li>
			   <li class="nav-item">
			      {% if user.is_authenticated %}
				   <a class="nav-link" href="{% url 'logout' %}">Logout</a>
				   <a class="nav-link" href="{% url 'profile' %}">Profile</a>
				   {% else %}
				   <a class="nav-link" href="{% url 'login' %}">Login</a>
				   {% endif %}
			   </li>
		  </ul>
		</div>
	  </div>
	</nav>

  <br>
  {% if messages %}
  	{% for message in messages %}
  	<div class="alert alert-{{ message.tags }}">
		  {{ message }}
	</div>

  	{% endfor %}
  {% endif %}


{%  block body %}
{%  endblock %}


</body>
</html>

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

 {% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="150px" width="400px" src="{{ item.item_image }}" class="card"/>
        </div>

         <div class="col-md-6">
             <h1>{{ object.item_name }}</h1>
             <h2>{{ object.item_desc }}</h2>
             <h3>${{ object.item_price }}</h3>
             <a href="{% url 'food:delete_item' item.id %}">Delete</a>

        </div>
    </div>
</div>

  {% endblock %}

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/templates/food/index.html

{% extends 'food/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

    {% block body %}

    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img  class="card" height="150px" width="400px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                <h6>{{ item.user_name }}</h6>

            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>


     {% endfor %}
    {% endblock %}




     this is the old code


        <ul>
            <li>

                <a href=""> {{ item.id }} -- {{ item.item_name }} </a>
            </li>
        </ul>






</body>
</html>

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/templates/food/item-delete.html
<form method="POST" action="">
    {% csrf_token %}
    <h2>Are you sure you want oe delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card rounded">
                <div class="card-header bg-success text-white text-center">
                    <div class="card-title">
                        <h3>Add Item</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                    {% csrf_token %}
                        {% for field in form %}
                            <div class="row sep">
                                <div class="col-sm-4">
                                    {{ field.label }}
                                </div>
                                <div class="col-sm-8">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <button class="btn-success rounded-pill sep" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token  %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <br>
                        <button class="btn btn-info text-white" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}





DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/templates/users/logout.html
<h1>You have been logged out </h1>

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px" src="{{ user.profile.image.url }}">

DjangoMasterclassBuild9RealWorldDjangoProjects/Project1FoodMenuApp/mysite/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <br>
                        <button class="btn btn-info text-white" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}